server:
   port: 8093 #设置服务端口
   servlet:
    context-path: / #设置服务路径     
spring:
   application:
      name: wonders-consumer-movie-hystrix
logging:
   level:
      root: INFO
      org.hibernate: INFO
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
      com.wondergroup: DEBUG
eureka:
   client:
      healthcheck:
         enabled: true
      registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
      fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
      service-url:
         defaultZone: http://user:password123@peer1:8761/eureka/
   instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${spring.application.instance_id:${server.port}}
feign:
  hystrix:
    enabled: true

    
