spring:
   application:
      name: gateway-zuul
server: 
   port: 8763
eureka:
   instance:
    prefer-ip-address: true
   client:
      service-url: # eureka服务地址
         defaultZone: http://user:password123@peer2:8762/eureka/
logging:
   level:
      root: INFO
      org.springframework.cloud.netflix.zuul: DEBUG        
zuul: 
  routes: 
    wonders-provider-user: 
      path: /myusers/** 
    wonders-provider-user2:
      path: /** 
    
    
    